#!/usr/bin/env bash
# prints the subdomain, record type and IP address from the argument parsed
domain=$1
subdomain=$2


get_dns_record() {
    local full_domain
    local record_type
    local destination
    full_domain=$1
    record_type=$(dig "$full_domain" +short | awk 'NR==1{if($0 ~ /:/){print "AAAA"} else {print "A"}}')
    destination=$(dig "$full_domain" +short)
    if [ -n "$destination" ]; then
        echo "The subdomain $2 is a $record_type record and points to $destination"
    else
        echo "No DNS record found for $full_domain"
    fi
}

if [ -n "$subdomain" ]; then
    get_dns_record "$subdomain.$domain" "$subdomain"
else
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        get_dns_record "$sub.$domain" "$sub"
    done
fi
