#!/usr/bin/env bash
# install nginx
apt-get -y update
sudo apt-get -y install nginx
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
/etc/init.d/nginx reload

sudo service nginx restart
echo "Hello World!" | sudo tee /var/www/html/index.html

#echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
