#!/usr/bin/env bash
# install nginx
apt-get -y update
sudo apt-get -y install nginx
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
/etc/init.d/nginx reload

echo "<!DOCTYPE html>
<html>
<head>
<title>Hello World!</title>
</head>
<body>
<h1>Hello World!</h1>
</body>
</html>" > /var/www/html/index.html

exit 0
