#!/usr/bin/env bash
#

apt-get update
apt-get install nginx -y

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

/etc/init.d/nginx reload

echo "
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/temp_redirect

ln -s /etc/nginx/sites-available/temp_redirect /etc/nginx/sites-enabled/

rm /etc/nginx/sites-enabled/default

/etc/init.d/nginx reload
