#!/usr/bin/env bash

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"


netstat -tuln | grep LISTEN | awk '{print $1, $4, $7}' | while read -r proto local foreign; do
    pid_program=$(lsof -i $proto@$local -sTCP:LISTEN -t -n -P)
    pid=$(echo "$pid_program" | awk '{print $2}')
    program=$(ps -p "$pid" -o comm=)

    echo "$proto        -      - $local                      -                   LISTEN      $pid/$program"
done
