#!/usr/bin/env bash
#A more advanced version of file 7

pid_file="/var/run/myscript.pid"

function SIGTERM_HANDLE()
{
    echo "I hate the kill command"
    cleanup_and_exit
}

trap SIGTERM_HANDLE SIGTERM

function SIGINT_HANDLE()
{
	echo "Y U no love me?!"
}

trap SIGINT_HANDLE SIGINT

function SIGQUIT_HANDLE()
{
    cleanup_and_exit
}

trap SIGQUIT_HANDLE SIGQUIT

function cleanup_and_quit()
{
    rm -f "$pid_file"
}

echo $$ > "$pid_file"

number=1

while [ $number -eq 1 ];
do
	echo "To infinity and beyond"
	sleep 2
done
