#!/usr/bin/env bash
#prints number from 1-100, fizz, buzz for multiples of 3 and 5, fizzbuzz for both
number=1

while [ $number -lt 100 ];
do
	if (( number % 3 == 0 )) && (( number % 5 == 0 ));
	then
		echo "FizzBuzz"
	elif (( number % 3 == 0 ));
	then
		echo "Buzz"
	elif (( number % 5 == 0 ));
	then
		echo "Fizz"
	else
		echo "$number"
	fi
	(( number++ ))
done
