#!/usr/bin/env bash
#prints "Best School" 9 times then "hi" the "Best School"

number=1

while [ $number -le 10 ]
do
	echo "Best School"
	if [ $number -eq 9 ]
	then
		echo "Hi"
	fi
	(( number++ ))
done
