#!/usr/bin/env bash
#displays:The content of the current directory in a list format

for i in $(ls); do
    if [[ ! $i == .* && -f $i ]];
    then
       echo "$i" | tr -d "[:digit:]" | tr -d "-"
    fi
done
