#!/usr/bin/env bash
#displays:The content of the current directory in a list format

for i in *; do
    if [[ ! $i == .* && -f $i ]];
    then
	name=$(echo "$i" | cut -d '-' -f 2-)
	echo "$name"
    fi
done
