#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements
sudo cp /etc/hosts /etc/hosts.bak

sudo sed 's/127.0.0.1[[:space:]]*localhost/127.0.0.2 localhost/' /etc/hosts

sudo sed '/facebook.com/ s/.*/8.8.8.8 facebook.com/' /etc/hosts
