#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements
sudo cp /etc/hosts /etc/hosts.bak

sed  "s 127.0.0.1[[:tab:]]localhost" >> /etc/hosts

#echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
